# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Soung',
            new_name='Song',
        ),
    ]
